import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useQuery } from "react-query";
import { useState } from "react";
import { Box, Text, Flex, Input, Select } from "@chakra-ui/react";
import useYoutube from "./hooks/useYoutube";

export default function Home() {
  const [videoId, setVideoId] = useState<string>("FaLBcSMVVuU");
  const [lan, setLan] = useState<string>("");

  const { renderYoutube, currentTime } = useYoutube({ videoId });

  const { data } = useQuery(`captions-${videoId}`, () =>
    fetch(`/api/captions?videoId=${videoId}`, {
      method: "GET",
    }).then((value) => value.json())
  );

  const { data: cap } = useQuery(
    `${videoId}${lan}`,
    () => lan && fetch(lan).then((value) => value.text())
  );

  return (
    <Box className={styles.container}>
      <Head>
        <title>Youtube Translator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Input
          id="videoId"
          value={videoId}
          onChange={(e) => setVideoId(e.target.value)}
        ></Input>
        {data && (
          <Select onChange={(e) => setLan(e.target.value)}>
            <option key="" value=""></option>
            {data.map((e: any) => (
              <option key={e.vssId} value={e.baseUrl}>
                {e.vssId}
              </option>
            ))}
          </Select>
        )}
        {renderYoutube()}
        <Box>{currentTime}</Box>
        <Box>
          {cap &&
            [
              ...cap
                .replaceAll(/&amp;#39;/g, "'")
                .matchAll(/<text start="(.*?)" dur="(.*?)">(.*?)<\/text>/g),
            ].map((e) => (
              <Flex key={e[0]}>
                <Box flex="1">{e[1]}</Box>
                <Box flex="1">{e[2]}</Box>
                <Box flex="5">
                  <Text>{e[3]}</Text>
                </Box>
              </Flex>
            ))}
        </Box>
      </main>

      <footer className={styles.footer}></footer>
    </Box>
  );
}
