import Head from "next/head";
import styles from "../styles/Home.module.css";
import YouTube, { YouTubeProps, YouTubePlayer } from "react-youtube";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  const [youtubePlayer, setYoutubePlayer] = useState<YouTubePlayer>();
  const [intervalCheck, setIntervalCheck] = useState<number>(0);
  const [playerState, setPlayerState] = useState<number>();
  const [currentTime, setCurrentTime] = useState<number>(0);
  const _onReady: YouTubeProps["onReady"] = (event) => {
    setYoutubePlayer(event.target);
  };
  const _onStateChange: YouTubeProps["onStateChange"] = (event) => {
    setPlayerState(event.target.getPlayerState());
  };

  useEffect(() => {
    const id = setInterval(() => {
      setCurrentTime(youtubePlayer?.getCurrentTime());
      if (playerState === 1) setIntervalCheck(intervalCheck + 1);
    }, 1000);
    return () => clearInterval(id);
  }, [youtubePlayer, playerState, intervalCheck]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{currentTime}</div>
        <YouTube
          videoId={"HxJoNjbJHjY"}
          onReady={_onReady}
          onStateChange={_onStateChange}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
